package com.lc.p2p.mapper.user;

import com.lc.p2p.model.user.FinanceAccount;

import java.util.Map;

public interface FinanceAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbggenerated Wed Nov 13 12:15:50 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbggenerated Wed Nov 13 12:15:50 CST 2019
     */
    int insert(FinanceAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbggenerated Wed Nov 13 12:15:50 CST 2019
     */
    int insertSelective(FinanceAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbggenerated Wed Nov 13 12:15:50 CST 2019
     */
    FinanceAccount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbggenerated Wed Nov 13 12:15:50 CST 2019
     */
    int updateByPrimaryKeySelective(FinanceAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbggenerated Wed Nov 13 12:15:50 CST 2019
     */
    int updateByPrimaryKey(FinanceAccount record);

    /**
     * 根据条件查询账户信息
     * @param
     * @return
     */
    FinanceAccount selectUserBalanceById(Integer uid);

    /**
     * 更新账户余额
     * @param paramMap
     * @return
     */
    int updateBalanceByUid(Map<String, Object> paramMap);

    /**
     * 将投资金额和收益返回到账户余额
     * @param paramMap
     * @return
     */
    int updateBalanceByIncomeMoney(Map<String, Object> paramMap);

    /**
     * 充值成功修改账户余额
     * @param params
     * @return
     */
    int updateBalanceByRechargeSuccess(Map<String, Object> params);
}