package com.lc.p2p.mapper.user;

import com.lc.p2p.model.user.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_user
     *
     * @mbggenerated Wed Nov 13 12:15:50 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_user
     *
     * @mbggenerated Wed Nov 13 12:15:50 CST 2019
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_user
     *
     * @mbggenerated Wed Nov 13 12:15:50 CST 2019
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_user
     *
     * @mbggenerated Wed Nov 13 12:15:50 CST 2019
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_user
     *
     * @mbggenerated Wed Nov 13 12:15:50 CST 2019
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_user
     *
     * @mbggenerated Wed Nov 13 12:15:50 CST 2019
     */
    int updateByPrimaryKey(User record);

    /**
     * 查询注册的总人数
     * @return
     */
    Long selectAllUserCount();

    /**
     * 根据手机号查询用户信息
     * @return
     */
    User selectUserByPhone(String phone);

    /**
     * 用户登陆验证
     * @param phone
     * @param loginPassword
     * @return
     */
    User selectUserByPhoneAndLoginPassword(String phone, String loginPassword);
}