package com.lc.p2p.mapper.loan;

import com.lc.p2p.model.loan.BidInfo;

import java.util.List;
import java.util.Map;

public interface BidInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Wed Nov 13 12:15:50 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Wed Nov 13 12:15:50 CST 2019
     */
    int insert(BidInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Wed Nov 13 12:15:50 CST 2019
     */
    int insertSelective(BidInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Wed Nov 13 12:15:50 CST 2019
     */
    BidInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Wed Nov 13 12:15:50 CST 2019
     */
    int updateByPrimaryKeySelective(BidInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Wed Nov 13 12:15:50 CST 2019
     */
    int updateByPrimaryKey(BidInfo record);

    /**
     * 查询总的投资金额
     * @return
     */
    Double selectAllBidMoney();

    /**
     * 根据产品id查询产品的额投资记录
     * @return
     */
    List<BidInfo> selectBidInfoListByLoanId(Map paramMap);

    Integer selectAllBidInfo(Map paramMap);
}